spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_profile_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Phanthang01@ # 👈 thay bằng đúng mật khẩu root của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update: không xóa data, chỉ tạo nếu thiếu
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always # cho phép chạy file data.sql khi khởi động
